<?php

namespace App\Http\Controllers\HT20;

use App\Http\Controllers\Base\ResouceController;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreApartment;
use App\Models\HT00\PostApartment;
use App\Models\HT00\PostCategory;
use App\Models\HT00\PostUser;
use App\Models\HT20\Group;
use App\Models\HT20\GroupUser;
use App\Models\HT20\User;
use App\Services\HT20\ApartmentService;
use App\Services\HT20\GroupService;
use App\Services\Impl\HT20\GroupServiceImpl;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str;

class GroupController extends ResouceController
{
    function __construct(GroupService $service)
    {
        $this->middleware('auth');
        parent::__construct($service, array('active' => 'groups'));
    }

    public function store(Request $request){
        $group=parent::storeRequest($request);
        if ($request->has('users')) {
            foreach ($request->users as $category) {
                $arr = explode("_", $category);
                GroupUser::updateOrCreate(
                    ['group_id' => $group->id, 'user_id' => $arr[0]],
                    ['modify_by' => Auth::id(), 'status' => $arr[1]]
                );
            }
        }
        return $group;
    }
    public function show($id)
    {
        $group= Group::find($id); // TODO: Change the autogenerated stub
        $group->users;
        return $group;
    }
}
